name: Publish to Pypi

on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
      python_version:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
