name: Publish to Docker and Pypi

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: make docker-build

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.8
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
