name: Validate changes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: make setup

      - name: Activate venv
        run: source .venv/bin/activate

      - name: Run tests
        run: make test

      - name: Run lint
        run: make lint
