name: Validate changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Install library
      run: poetry install --no-interaction .
 
    - name: Activate venv
      run: source .venv/bin/activate

    - name: Mypy test
      run: .venv/bin/mypy --install-types --non-interactive .

    - name: Install dependencies
      run: make setup

    - name: Run tests
      run: make test

    - name: Run flake8
      run: make flake8

    - name: Install mypy types
      run: mypy --install-types --non-interactive .

    - name: Run mypy
      run: make mypy
